name: cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Täglich um 01:00 Uhr
  workflow_dispatch:

jobs:
  cleanup-old-runs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh run ls --all --limit 40 --workflow "update" --json databaseId -q ".[].databaseId" | xargs -n1 gh run delete
